### ISSUE TITLE
შენიშვნები

### ISSUE THREAD

**Issue by giorgik08** [valeri879/vereloft#1]
1. ზედა ნავიგაციაში მაუსის მიტანისას ჰოვერზე გამოჩნდეს მაუსის იკონკა რომ ეტყობოდეს რომ მიტანილია და დაჭერადია.
2. ვიდეოს ბექრაუნდად უნდა იყოს youtube-ს ლინკი და არა ფიზიკური მისამართი.
3. Read More-ზე დაჭერისას ჩამოდიოდეს About Us სექციაზე.
4. მენიუში გამორჩენილია Our Office და შესაბამისად დაჭერისას რომ გადადიოდეს სექციაზე.
5. ენების გადამრთველზე სადაც en ge და ru იქნება მაგათ შორის დაშორება იქნება შესამცირებელი
6. ასევე ენებს უნდა შემოეხვიოს <a> ტეგი. შემოხვევა ვცადე და უშნოდ გამოვიდა, გასტილვა ჭირდება
7. სქროლვისას როცა სექცია იცვლება fixed ნავიგაციაში იქნებ მოინიშნოს ხოლმე რომელი სექციაა აქტიური

**Comment by valeri879** [comment]
OK
