### ISSUE TITLE
შენიშვნები #2

### ISSUE THREAD

**Issue by giorgik08** [valeri879/vereloft#2]
1. ზოგგან p ტეგს აქვს გაწერილი კლასი, მაგალითად about us სექციაში არის <p class="sl-p">. კარგი იქნება თუ მოაშორებ p-ს კლასს და გახვალ სექციის კლასით მაგ p-ზე

2. ფუტერში იკონკები არის ძალიან პატარა, 250%-ზე დავაზუმე ეკრანი და მაინც ძალიან პატარები ჩანს და აშკარად ეტყობა რო გაზრდა ჭირდება

3. ინსტაგრამის იკონკა რომ ჩაემატოს პროექტებშიც და ფუტერშიც

**Comment by valeri879** [comment]
OK

**Comment by giorgik08** [comment]
ფუტერში სოციალური ქსელების იკონკებს შემოვახვიე ლინკი და სტილი დაეკარგა ეგეც გასასწორებელია

**Comment by giorgik08** [comment]
ფუტერში LET'S SOCIALIZE-ს თავზე უნდა იყოს ზევით ასასვლელი იკონკა რომბში და ეგეც არაა

**Comment by giorgik08** [comment]
საკონტაქტო ფორმის თავზე ტექსტი მინდა, რომელიც უნდა გამოვაჩინო გაგზავნის შემდეგ წარმატებით გაიგზავნა თუ არა
