### ISSUE TITLE
შენიშვნები

### ISSUE THREAD

**Issue by giorgik08** [valeri879/vereloft#3]
მთლიან ეკრანზე პრობლემები მგონი არ არის, ყოველ შემთხვევაში ჯერ ვერ შევნიშნე. რამოდენიმე შენიშვნა მობილურის დროს რესფონსივზე

1. ნავიგაციის ასარჩევი რომ არის იქ რომ სხვა სექციაზე გადავიდე მაინც MAIN რჩება ტექსტად
2. მთავარ გვერდზე სლაიდერის ადგილას მოკლე ტექსტი არ ჩანს
3. About Us ძალიან ჩამოგრძელებულია და იქნებ რამე მოვუხერხოთ
4. პრაის ლისტში პაკეტის არჩევისას არ გამოდის დეტალური ვარიანტი.
5. სტარტაპ პროექტები სადაც  იქნებ ეგ რესფონსივზე 2-2ად დავალაგოთ
6. სასწაულისამებრ კონტაქტში მეილის გვერდით ჩნდება გასადიდებელი ღილაკი :laughing:

**Comment by valeri879** [comment]
5. სტარტაპ პროექტები სადაც იქნებ ეგ რესფონსივზე 2-2ად დავალაგოთ
ეს ვცადე მაგრამ არ მოუხდა ძალიან პატარები გამოჩნდა

**Comment by valeri879** [comment]
about us გავასწორე

**Comment by valeri879** [comment]
main სქროლ ტოპის ვარიანტში მაქვს დატოვილი სულ უნდა ჩანდეს

**Comment by valeri879** [comment]
მთავარ გვერდზე სლაიდერის ადგილას მოკლე ტექსტი არ ჩანს << ესეც შესწორებულია

**Comment by valeri879** [comment]
სასწაულისამებრ კონტაქტში მეილის გვერდით ჩნდება გასადიდებელი ღილაკი <<< ესეც შევასწორე
