### ISSUE TITLE
მთავარი ვიდეო

### ISSUE THREAD

**Issue by valeri879** [valeri879/vereloft#7]
ვიდეოზე არ უნდა იყოს youtube-ს პეიერი

**Comment by valeri879** [comment]
ვიდეოზე რომ გაითიშოს youtube-ს ღილაკები და გაშვებული იყოს ლუპში

**Comment by giorgik08** [comment]
ყველანაირი ინფორმაცია მოვაშორე ვიდეოს, ერთადერთი mouse over-ზე ჩნდება youtube-ს ლოგო კუთხეში რომელიც არ შორდება, youtube არ იძლევა საშუალებას
